INSERT INTO applications (
  user_id,
  cwid,
  full_name,
  discord,
  skill_level,
  hackathon_experience,
  hear_about_us,
  why_attend,
  project_experience,
  future_plans,
  fun_fact,
  self_description,
  links,
  teammates,
  referral_email,
  dietary_restrictions_extra,
  tshirt_size,
  agree_to_terms,
  status,
  created_at
) VALUES
(
  'user_2w4iVs7wAQoSrlzCKEqLi0iH8sE',
  '12345678',
  'Alice Johnson',
  'alice#1111',
  'Beginner',
  'First timer',
  'Discord',
  'To learn and build something cool',
  'Built a weather app with React',
  'Become a frontend developer',
  'I have a pet turtle',
  'Curious and fast learner',
  'https://github.com/alice',
  'bob@dahacks.com,charlie@dahacks.com',
  'referral@dahacks.com',
  'Vegan',
  'M',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_3xqKdL9zBYmXutGHwPpRb4Na0cTy',
  '87654321',
  'Bob Smith',
  'bob#2222',
  'Intermediate',
  'Participated in 2 hackathons',
  'Instagram',
  'Looking to network and explore ideas',
  'Built a to-do list with Firebase',
  'Start a tech company',
  'I juggle in my free time',
  'Creative and driven',
  'https://bob.dev',
  '',
  '',
  '',
  'L',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_J0uVxKwQ8AcR5Zel9FtHCBgN2pWu',
  '13579246',
  'Clara Zheng',
  'clara#3333',
  'Advanced',
  'Won 1st prize at MLH',
  'Twitter',
  'Challenge myself with new APIs',
  'Created a crypto tracker app',
  'Contribute to open source',
  'I can solve a Rubik’s cube blindfolded',
  'Loves AI and design',
  'https://claraz.dev',
  'dan@hack.xyz',
  '',
  '',
  'S',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_AqE0yLtW73JkcUZvF6DpNH2mwfxl',
  '19283746',
  'Daniel Lee',
  'daniel#4444',
  'Beginner',
  'Attended 1 online hackathon',
  'Class',
  'To learn teamwork and project building',
  'Made a Python CLI tool',
  'Get internship next summer',
  'I play 5 instruments',
  'Energetic and focused',
  '',
  '',
  '',
  'Halal',
  'M',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_MZkTy09HEfNqgBL3aWuvYDseC24p',
  '11235813',
  'Emily Nguyen',
  'emily#5555',
  'Intermediate',
  'Helped build a fintech app',
  'Friend',
  'Make a social impact',
  'Developed an expense tracker',
  'Launch my own startup',
  'I’ve never missed a hackathon',
  'Social and full of ideas',
  'https://emily.codes',
  '',
  'friend@uni.edu',
  '',
  'XS',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_NhtV23Xs9fPCDjYUqKEzMaW14oBd',
  '24681357',
  'Frank Torres',
  'frank#6666',
  'Beginner',
  'High school coder club',
  'Email',
  'To get better at coding fast',
  'Simple game in Unity',
  'Become a game dev',
  'I build custom keyboards',
  'Hardworking and curious',
  '',
  '',
  '',
  '',
  'XL',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_vbA03yX5Cm7EGtk9LjW2NHpFsoqQ',
  '31415926',
  'Grace Kim',
  'grace#7777',
  'Advanced',
  'Mentored at hackathons',
  'Website',
  'Meet fellow hackers',
  'Built ML models for text classification',
  'Join AI research lab',
  'I danced in a K-pop cover team',
  'Tech + creativity = me',
  'https://grace.dev',
  '',
  '',
  '',
  'M',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_Qt6ZJXW5mvFGhkuRDEyopCwl97an',
  '11224455',
  'Henry Zhao',
  'henry#8888',
  'Intermediate',
  'Built a group finder app',
  'Discord',
  'Build something people use',
  'React + Supabase project',
  'Work in product at a startup',
  'I love spicy food',
  'Empathetic product thinker',
  '',
  'grace@dev.io',
  '',
  '',
  'L',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_H8zMrQF0BGnLpUvDK24XwmTfq3so',
  '90909090',
  'Isabella Lopez',
  'isa#9999',
  'Beginner',
  'Heard about it from teacher',
  'Classroom',
  'Learn from others',
  'Arduino project for school',
  'Study robotics at college',
  'I speak 3 languages',
  'Hands-on learner',
  '',
  '',
  '',
  '',
  'M',
  true,
  'submitted',
  CURRENT_TIMESTAMP
),
(
  'user_YLpPoIkUDFghTmrnzOeAxcv3KqRb',
  '10020030',
  'Jay Patel',
  'jay#0000',
  'Advanced',
  'Won 3 hackathons',
  'LinkedIn',
  'To build with new tech',
  'Blockchain + frontend experience',
  'Build a dev tool SaaS',
  'I used to run a meme page',
  'Obsessed with efficiency',
  'https://jay.tech',
  'emily@dev.com,clara@dev.com',
  '',
  'Vegetarian',
  'L',
  true,
  'submitted',
  CURRENT_TIMESTAMP
);
